global proc int qlTruncateCache() 
{
	string $sims[];
	string $clothes[];
	string $sim;
	string $cloth;
	string $nodes[];

	$clothes = qlGetClothes();
	
	if(size($clothes) == 0) 
	{
		$sims = qlGetSimulators();
		if(size($sims)==0) return 0;
		
		for($sim in $sims)
		{
			$nodes = qlGetClothesBelongToThisSolver($sim);
			$clothes = stringArrayCatenate($clothes, $nodes);
		}
		
	}

	for($cloth in $clothes)
	{
		qlTruncateSimCache($cloth);
	}

	return 1;
}
